# Generated by Django 4.2.16 on 2024-10-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_id', models.IntegerField(default=0)),
                ('comment_owner', models.CharField(blank=True, default='', max_length=255)),
                ('replied_to', models.CharField(blank=True, default='', max_length=255)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPerformanceForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Evaluator', 'Evaluator'), ('Teacher', 'Teacher')], default='', max_length=255)),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('email_address', models.CharField(blank=True, default='', max_length=255)),
                ('position', models.CharField(blank=True, choices=[('Teacher I', 'Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher IV', 'Master Teacher IV')], default='', max_length=255)),
                ('job_started', models.DateTimeField(blank=True, null=True)),
                ('job_ended', models.DateTimeField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, choices=[('Junior High School', 'Junior High School'), ('Senior High School', 'Senior High School')], default='', max_length=255)),
                ('department', models.CharField(blank=True, choices=[('Science', 'Science'), ('Filipino', 'Filipino'), ('Mathematics', 'Mathematics'), ('English', 'English')], default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('confirm_password', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_owner', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='RatingSheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RedirectHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=255)),
                ('token', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('redirect_url', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResultBasedForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('school_name', models.CharField(blank=True, default='', max_length=255)),
                ('school_address', models.CharField(blank=True, default='', max_length=255)),
                ('school_type', models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural')], default='', max_length=255)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255)),
                ('email_address', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('confirm_password', models.CharField(blank=True, default='', max_length=255)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='school_logo')),
            ],
        ),
    ]
