# Generated by Django 4.2.16 on 2024-10-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='educations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
