# Generated by Django 4.2.16 on 2024-10-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_people_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='COTForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('evaluated_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('content', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='IPCRFForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('evaluator_id', models.CharField(blank=True, default='', max_length=255)),
                ('form_type', models.CharField(blank=True, choices=[('PART 1', 'PART 1'), ('PART 2', 'PART 2'), ('PART 3', 'PART 3')], default='', max_length=255)),
                ('content_for_teacher', models.JSONField(blank=True, default=dict)),
                ('content_for_evaluator', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RPMSAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_work_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=255)),
                ('attachment_id', models.CharField(blank=True, default='', max_length=255)),
                ('streams_type', models.CharField(blank=True, default='', max_length=255)),
                ('file', models.FileField(upload_to='rpms_attachments')),
                ('grade', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RPMSClassWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rpms_folder_id', models.CharField(blank=True, default='', max_length=255)),
                ('class_work_id', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('objectives', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='RPMSFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(blank=True, default='', max_length=255)),
                ('employee_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rpms_folder_id', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('verification_link', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IndividualPerformanceForm',
        ),
        migrations.DeleteModel(
            name='RatingSheetForm',
        ),
        migrations.DeleteModel(
            name='RedirectHandler',
        ),
        migrations.DeleteModel(
            name='ResultBasedForm',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to='comment/'),
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
