# Generated by Django 4.2.16 on 2024-10-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cotform_ipcrfform_mainadmin_rpmsattachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='mainadmin',
            name='action_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='people',
            name='action_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='action_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
