# Generated by Django 4.2.16 on 2024-10-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_comment_is_seen_mainadmin_action_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='school_action_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='commented',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='post',
            name='content_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
