# Generated by Django 4.2.16 on 2024-10-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_school_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
