# Generated by Django 4.2.16 on 2024-10-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainadmin',
            name='role',
            field=models.CharField(blank=True, default='ADMIN', max_length=10),
        ),
    ]
