# Generated by Django 4.2.16 on 2024-10-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_cotform_is_checked_ipcrfform_is_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
