# Generated by Django 4.2.16 on 2024-10-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_people_is_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='fullname',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cotform',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=255),
        ),
    ]
