# Generated by Django 4.2.16 on 2024-10-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_people_fullname_alter_cotform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='is_deactivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='mentions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
