# Generated by Django 4.2.16 on 2024-10-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_postattachment_remove_comment_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmsclasswork',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rpmsfolder',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='rpms_folders/'),
        ),
    ]
