# Generated by Django 4.2.16 on 2024-10-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_rpmsclasswork_due_date_rpmsfolder_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotform',
            name='is_for_teacher_proficient',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipcrfform',
            name='is_checked_by_evaluator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipcrfform',
            name='is_for_teacher_proficient',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rpmsattachment',
            name='streams_type',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='', max_length=255),
        ),
    ]
