# Generated by Django 4.2.16 on 2024-10-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_cotform_is_for_teacher_proficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpmsattachment',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
