# Generated by Django 4.2.16 on 2024-10-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_rpmsattachment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcrfform',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='position',
            field=models.CharField(blank=True, choices=[('Teacher I', 'Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher IV', 'Master Teacher IV')], default='Teacher I', max_length=255),
        ),
    ]
