# Generated by Django 4.2.16 on 2024-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_ipcrfform_is_expired_alter_people_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpmsattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='rpms_attachments'),
        ),
    ]
