# Generated by Django 4.2.16 on 2024-10-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_rpmsattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationlink',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
