# Generated by Django 4.2.16 on 2024-11-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_verificationlink_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_declined",
            field=models.BooleanField(default=False),
        ),
    ]
