# Generated by Django 4.2.16 on 2024-11-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_postattachment_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotform",
            name="school_year",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
