"""
Django settings for bnahs project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h4n&*x5w1v87vt3ok^ry^(-n#vt33fjm37i&lz68$ghko865hm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# MY_HOST = 'http://127.0.0.1:8000/'  # Set your preferred host
MY_HOST = 'https://bnahs.pythonanywhere.com/'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    
    'corsheaders', 
    
    'backend.apps.BackendConfig',
    'frontend.apps.FrontendConfig',
    
]

MIDDLEWARE = [
    
    'corsheaders.middleware.CorsMiddleware', 
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'whitenoise.middleware.WhiteNoiseMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bnahs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bnahs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

TIME_ZONE = 'Asia/Manila'  # Set your preferred time zone
USE_TZ = True  # Enable time zone support


USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
 
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]


MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Allow your frontend to access the backend:
# CORS_ALLOWED_ORIGINS = [
#     "https://your-frontend-domain.com",
#     "http://localhost:8000",
# ]

# For development purposes, you can allow all origins, but it's not recommended for production
CORS_ALLOWED_ORIGINS = [
    'https://bnahs.pythonanywhere.com',
    'http://www.deped-performance-evaluation-system3211.online',
    "http://localhost:8000", # For development purposes
    "http://127.0.0.1:8000", # For development purposes
]
CORS_ORIGIN_ALLOW_ALL = True 

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'Authorization',
    'Content-Type',
    'credentials',  # Add this line
    'X-Requested-With',  # Ensure this header is allowed
    'X-CSRFToken', 
]


SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = True

CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE = True



SESSION_ENGINE = 'django.contrib.sessions.backends.db'


# Default email backend settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vincelance62@gmail.com' # Email address
EMAIL_HOST_PASSWORD = 'ozoxahnrfrsdaerj' # Generated email password appp 'ozox ahnr frsd aerj'

OPEN_AI_KEY = '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'